import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';

const translations = {
  en: {
    adminPanel: 'Admin Panel',
    adminSubtitle: 'Monitor users, crops, bids, and market activity',
    english: 'English',
    marathi: 'Marathi',
    dashboard: 'Dashboard',
    users: 'Users',
    crops: 'Crops',
    bids: 'Bids',
    transactions: 'Transactions',
    marketPrices: 'Market Prices',
    settings: 'Settings',
    logout: 'Logout',
    version: 'Version 1.0.0',
    dashboardOverview: 'Dashboard Overview',
    totalUsers: 'Total Users',
    pendingApprovals: 'Pending Approvals',
    totalCrops: 'Total Crops',
    totalBids: 'Total Bids',
    totalTransactions: 'Total Transactions',
    farmers: 'Farmers',
    traders: 'Traders',
    officers: 'Officers',
    available: 'Available',
    sold: 'Sold',
    pending: 'Pending',
    accepted: 'Accepted',
    totalValue: 'Total Value',
    recentUsers: 'Recent Users',
    recentTransactions: 'Recent Transactions',
    approved: 'Approved',
    noRecentUsers: 'No recent users',
    noRecentTransactions: 'No recent transactions',
    to: 'to',
    userManagement: 'User Management',
    exportCsv: 'Export CSV',
    exportPdf: 'Export PDF',
    search: 'Search',
    allRoles: 'All Roles',
    allStatus: 'All Status',
    role: 'Role',
    status: 'Status',
    user: 'User',
    email: 'Email',
    actions: 'Actions',
    showing: 'Showing',
    of: 'of',
    noUsersFound: 'No users found',
    cropManagement: 'Crop Management',
    crop: 'Crop',
    farmer: 'Farmer',
    quantity: 'Quantity',
    basePrice: 'Base Price',
    noCropsFound: 'No crops found',
    bidManagement: 'Bid Management',
    trader: 'Trader',
    bidAmount: 'Bid Amount',
    date: 'Date',
    noBidsFound: 'No bids found',
    totalTransactionValue: 'Total Transaction Value',
    transactionId: 'Transaction ID',
    amount: 'Amount',
    noTransactionsFound: 'No transactions found',
    addPrice: 'Add Price',
    minPrice: 'Min Price',
    maxPrice: 'Max Price',
    avgPrice: 'Avg Price',
    unit: 'Unit',
    lastUpdated: 'Last updated',
    noMarketPricesAvailable: 'No market prices available',
    editMarketPrice: 'Edit Market Price',
    addMarketPrice: 'Add Market Price',
    cropNameEnglish: 'Crop Name (English)',
    cropNameMarathi: 'Crop Name (Marathi)',
    save: 'Save',
    cancel: 'Cancel',
    settingsTitle: 'Settings',
    accountInformation: 'Account Information',
    fullName: 'Full Name',
    username: 'Username',
    phone: 'Phone',
    rolePermissions: 'Role & Permissions',
    currentRole: 'Current Role',
    permissions: 'Permissions',
    manageUsers: 'Manage Users',
    manageCrops: 'Manage Crops',
    manageBids: 'Manage Bids',
    viewTransactions: 'View Transactions',
    manageMarketPrices: 'Manage Market Prices',
    exportData: 'Export Data (CSV/PDF)',
    manageAdmins: 'Manage Admins (Superadmin Only)',
    systemInformation: 'System Information',
    environment: 'Environment',
    lastLogin: 'Last Login',
    production: 'Production',
    active: 'Active',
    yes: 'Yes',
    no: 'No'
  },
  mr: {
    adminPanel: 'प्रशासन पॅनल',
    adminSubtitle: 'वापरकर्ते, पिके, बोली आणि बाजार हालचाली पहा',
    english: 'English',
    marathi: 'मराठी',
    dashboard: 'डॅशबोर्ड',
    users: 'वापरकर्ते',
    crops: 'पिके',
    bids: 'बोली',
    transactions: 'व्यवहार',
    marketPrices: 'बाजारभाव',
    settings: 'सेटिंग्ज',
    logout: 'लॉगआउट',
    version: 'आवृत्ती 1.0.0',
    dashboardOverview: 'डॅशबोर्ड आढावा',
    totalUsers: 'एकूण वापरकर्ते',
    pendingApprovals: 'प्रलंबित मंजुरी',
    totalCrops: 'एकूण पिके',
    totalBids: 'एकूण बोली',
    totalTransactions: 'एकूण व्यवहार',
    farmers: 'शेतकरी',
    traders: 'व्यापारी',
    officers: 'अधिकारी',
    available: 'उपलब्ध',
    sold: 'विकलेले',
    pending: 'प्रलंबित',
    accepted: 'स्वीकृत',
    totalValue: 'एकूण किंमत',
    recentUsers: 'अलीकडील वापरकर्ते',
    recentTransactions: 'अलीकडील व्यवहार',
    approved: 'मंजूर',
    noRecentUsers: 'अलीकडील वापरकर्ते नाहीत',
    noRecentTransactions: 'अलीकडील व्यवहार नाहीत',
    to: 'ते',
    userManagement: 'वापरकर्ता व्यवस्थापन',
    exportCsv: 'CSV निर्यात',
    exportPdf: 'PDF निर्यात',
    search: 'शोधा',
    allRoles: 'सर्व भूमिका',
    allStatus: 'सर्व स्थिती',
    role: 'भूमिका',
    status: 'स्थिती',
    user: 'वापरकर्ता',
    email: 'ईमेल',
    actions: 'कृती',
    showing: 'दाखवत आहे',
    of: 'पैकी',
    noUsersFound: 'वापरकर्ते सापडले नाहीत',
    cropManagement: 'पीक व्यवस्थापन',
    crop: 'पीक',
    farmer: 'शेतकरी',
    quantity: 'प्रमाण',
    basePrice: 'मूळ किंमत',
    noCropsFound: 'पिके सापडली नाहीत',
    bidManagement: 'बोली व्यवस्थापन',
    trader: 'व्यापारी',
    bidAmount: 'बोली रक्कम',
    date: 'दिनांक',
    noBidsFound: 'बोली सापडल्या नाहीत',
    totalTransactionValue: 'एकूण व्यवहार मूल्य',
    transactionId: 'व्यवहार आयडी',
    amount: 'रक्कम',
    noTransactionsFound: 'व्यवहार सापडले नाहीत',
    addPrice: 'भाव जोडा',
    minPrice: 'किमान भाव',
    maxPrice: 'कमाल भाव',
    avgPrice: 'सरासरी भाव',
    unit: 'एकक',
    lastUpdated: 'शेवटचे अद्यतन',
    noMarketPricesAvailable: 'बाजारभाव उपलब्ध नाहीत',
    editMarketPrice: 'बाजारभाव संपादित करा',
    addMarketPrice: 'बाजारभाव जोडा',
    cropNameEnglish: 'पीक नाव (इंग्रजी)',
    cropNameMarathi: 'पीक नाव (मराठी)',
    save: 'जतन करा',
    cancel: 'रद्द करा',
    settingsTitle: 'सेटिंग्ज',
    accountInformation: 'खाते माहिती',
    fullName: 'पूर्ण नाव',
    username: 'वापरकर्तानाव',
    phone: 'फोन',
    rolePermissions: 'भूमिका आणि परवानग्या',
    currentRole: 'सध्याची भूमिका',
    permissions: 'परवानग्या',
    manageUsers: 'वापरकर्ते व्यवस्थापित करा',
    manageCrops: 'पिके व्यवस्थापित करा',
    manageBids: 'बोली व्यवस्थापित करा',
    viewTransactions: 'व्यवहार पहा',
    manageMarketPrices: 'बाजारभाव व्यवस्थापित करा',
    exportData: 'डेटा निर्यात (CSV/PDF)',
    manageAdmins: 'अॅडमिन व्यवस्थापित करा (फक्त सुपरअॅडमिन)',
    systemInformation: 'प्रणाली माहिती',
    environment: 'परिसर',
    lastLogin: 'शेवटचा लॉगिन',
    production: 'प्रॉडक्शन',
    active: 'सक्रिय',
    yes: 'होय',
    no: 'नाही'
  }
};

const LanguageContext = createContext(null);

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => localStorage.getItem('dashboardLanguage') || 'en');

  useEffect(() => {
    localStorage.setItem('dashboardLanguage', language);
  }, [language]);

  const value = useMemo(() => ({
    language,
    setLanguage,
    t: (key) => translations[language]?.[key] || translations.en[key] || key
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
